name: cutmate
description: Your AI wingman for weight loss. CutMate helps men achieve their cutting goals through personalized AI meal recommendations, progress tracking, and motivational support—all with a friendly, no-pressure approach.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
